### ISSUE TITLE
Backup (Export to Password Pump) does not save customized group names

### ISSUE THREAD

**Issue by scootercommuter** [seawarrior181/PasswordPump_II#10]
In the Password Pump Gui I did an Export to Password Pump file, with encryption.  On my spare password pump I did a Factory Reset, set the password, and did an Import from Password Pump (file).  The Import worked just fine.  However I had previously customized three of the Group Names, and the customized names had been reverted to the non-customized group names.  THEN, on the original Password Pump (from which I'd done the Export) the un-customized group names showed up!  SO, in the Password Pump GUI I updated the group names I had previously customized.  At this point one of two things will happen.  If you do a long-click on the Password Pump before you close the GUI, the new names are not saved.  If you close the GUI first, the changes are saved on the Password Pump itself _as long as you Reset the device_.  It could be that just restarting it would do the trick.  At this point I had to repeat the process on my backup Password Pump.  In case it matters: one of the PPs was a Rotary Encoder model and the one I used for the original backup was the Joystick model.  Both had been upgraded previously to version 2.0.8, and the GUI is version 2.0.8.

**Comment by seawarrior181** [comment]
ScooterCommuter,

Some of this is expected behavior, albeit a shortcoming that should be addressed.  Presently, when you backup your PasswordPump to a PasswordPump Export File format (a practice that is highly encouraged, encrypted), the custom names of the groups/categories are NOT saved, therefore they must be re-entered when restoring a PasswordPump from a PasswordPump Export File.  This will be addressed in a future release.  

There is nothing about creating a PasswordPump Export File that touches the custom group names, therefore I am baffled by the behavior you witnessed whereby the customized group names reverted back to the defaults after you created the export file.  I create a PasswordPump Export File a couple of times a week and I have never lost the custom group names, so this is very concerning. 

I will now work with the PasswordPumpGUI to see if I can reproduce the balance of the bad behavior you saw.

Thanks,
Dan

**Comment by seawarrior181** [comment]
The defect whereby group names are not correctly handled between the PasswordPump and the PasswordPumpGUI is addressed in firmware release 2.0.8.02, available for download in the usual locations.  Thanks for reporting this defect.  Work to export the customized group names to the PasswordPump format is up next.

Best,
Dan
