### ISSUE TITLE
Some v2_0_5 fonts do not display correctly

### ISSUE THREAD

**Issue by JSField** [seawarrior181/PasswordPump_II#4]
I originally used v2_0_4 firmware and it was working good. I noticed that I didn't have some of the settings, like the Font in Settings, so I upgraded to 2_0_5, which also worked. I decided to try changing to a different font (for screen readability). The line spacing seemed to be off with some of the fonts I tried, but with one of the fonts (not sure which one), the screen went blank. If I reboot the device, the screen is black, until I click and turn the knob and then the numbers show. But once I enter the master password, it is basically dark again. Sometimes half a number shows. I flashed back to 2_0_4 and it is ok, but if I flash back to 2_0_5, screen is blank.

**Comment by seawarrior181** [comment]
JSField,

Thank you for reporting this, and apologies for the trouble.  The 2.0.5 code isn't "released" yet.  I thought I had removed all of the problematic fonts, but it seems there is one remaining.  The line spacing is a little off with all of the fonts, there's no space between the lines; so I'm on the fence with respect to continuing to move in that direction.  The library I'm now using isn't allowing me to specify the space between the lines.  I recommend sticking with 2.0.4 for now.  I have fixed a couple of minor bugs in 2.0.5, I will try to back port those fixes to 2.0.4.

Best,
Dan Murphy
dan-murphy@comcast.net
5volts.org

**Comment by JSField** [comment]
No worries Dan. I am just wondering why when I re-flash 2.0.5 back, it seems to keep the problematic font and the screen is basically black. 2.0.5 looked ok until I changed the font. Is the font info stored on the eeprom? I thought when I re-flashed it would revert to the default font.
Jeff

**Comment by seawarrior181** [comment]
Hi Jeff,

Yes, the font that you've selected is stored in EEprom, so in a way you've (or, I've) bricked it out of 2.0.5.  If you really want to install 2.0.5:  

1) Flash to 2.0.4
2) Via PasswordPumpGUI, File->Export->Export to PasswordPump
3) On the device, Factory Reset (this clears out EEprom)
4) Flash to 2.0.5
5) On the device, reestablish a master password
6) Via PasswordPumpGUI, File->Import->Import from PasswordPump
7) Delete the file you exported in step #2 and empty your trash, or otherwise encrypt the file.

If you identify the offending font please let me know which one it is, and let me know how you make out.

Best,
Dan

**Comment by JSField** [comment]
Ok, the bad font is the 'Fixednums8x16' one. The only really usable fonts are any of the 5x7 fonts.

Thanks,
Jeff

**Comment by seawarrior181** [comment]
Thanks Jeff.  I noticed that a while back and update the code and the comments, but neglected to update the binary.  I will try to do that this weekend.

Best,
Dan

**Comment by seawarrior181** [comment]
I've updated the .bin files in the M0 and M4 subdirectories.

Best,
Dan
